# Generated by Django 3.2.4 on 2021-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_remove_poll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
