# Generated by Django 3.2.4 on 2021-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_poll_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
