# Generated by Django 3.2.4 on 2021-06-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_auto_20210614_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A_tester',
        ),
        migrations.DeleteModel(
            name='B_tester',
        ),
    ]
