# Generated by Django 3.2.4 on 2021-06-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_auto_20210614_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
    ]
