# Generated by Django 3.2.4 on 2021-06-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_rename_polls_poll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Pool',
        ),
    ]
