# Generated by Django 3.2.4 on 2021-06-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_rename_poll_pool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
