# Generated by Django 3.2.4 on 2021-06-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0012_delete_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMS_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('firt_name', models.CharField(max_length=100)),
                ('personal_id', models.CharField(max_length=100)),
                ('status_pool', models.CharField(max_length=100)),
                ('class_in', models.CharField(max_length=100)),
                ('class_out', models.CharField(max_length=100)),
                ('office_in', models.CharField(max_length=100)),
                ('office_out', models.CharField(max_length=100)),
            ],
        ),
    ]
