# Generated by Django 3.2.4 on 2021-06-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_bpms_main_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BPMS_main',
            new_name='People',
        ),
    ]
