# Generated by Django 3.2.4 on 2021-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_rename_bpms_main_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=40)),
                ('custodian_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
        migrations.RenameField(
            model_name='people',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
