# Generated by Django 3.2.4 on 2021-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_auto_20210618_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='username',
            field=models.CharField(default=models.CharField(max_length=50), max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='class_in',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='class_out',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='office_in',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='office_out',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='status_pool',
            field=models.BooleanField(),
        ),
    ]
