# Generated by Django 3.2.4 on 2021-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_auto_20210618_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='type',
        ),
        migrations.AddField(
            model_name='people',
            name='occupation',
            field=models.CharField(default='Student', max_length=8),
        ),
        migrations.AlterField(
            model_name='people',
            name='class_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='class_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='office_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='office_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='status_pool',
            field=models.BooleanField(default=True),
        ),
    ]
