# Generated by Django 3.2.5 on 2021-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_auto_20210714_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_out',
            field=models.DateField(null=True),
        ),
    ]
