# Generated by Django 3.2.5 on 2021-07-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_auto_20210714_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='today_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_out',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
