# Generated by Django 3.2.5 on 2021-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_auto_20210714_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
