# Generated by Django 3.2.5 on 2021-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_alter_record_time_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='class_in',
            new_name='class1_in',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='class_out',
            new_name='class1_out',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='office_in',
            new_name='class2_in',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='office_out',
            new_name='class2_out',
        ),
        migrations.AddField(
            model_name='people',
            name='library_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='library_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='people',
            name='office1_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='office1_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='people',
            name='office2_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='office2_out',
            field=models.BooleanField(default=True),
        ),
    ]
