# Generated by Django 3.2.5 on 2021-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_auto_20210715_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
