# Generated by Django 3.2.5 on 2021-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
