# Generated by Django 3.2.5 on 2021-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_location_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
