# Generated by Django 3.2.5 on 2021-08-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_auto_20210807_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='venue_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.location'),
        ),
    ]
