# Generated by Django 3.2.5 on 2021-08-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0033_alter_people_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='venue_name',
            field=models.ForeignKey(default='Pool', on_delete=django.db.models.deletion.CASCADE, to='Dashboard.location'),
        ),
    ]
