# Generated by Django 3.2.5 on 2021-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0035_alter_people_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='color',
            new_name='initial',
        ),
    ]
