# Generated by Django 3.2.5 on 2021-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0036_rename_color_location_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='initial',
        ),
        migrations.AddField(
            model_name='location',
            name='ip_enter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ip_leave',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
