# Generated by Django 3.2.4 on 2021-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_polls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Visitor',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='poll_id',
            new_name='visitor_id',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='status',
            new_name='visitor_name',
        ),
    ]
