# Generated by Django 3.2.4 on 2021-06-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20210614_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status_id',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='unidentified', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='unidentified', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(default='BIT', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=2021, max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=25),
        ),
    ]
