# Generated by Django 3.2.4 on 2021-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20210617_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
