# Generated by Django 3.2.4 on 2021-06-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_alter_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=8),
        ),
    ]
