# Generated by Django 3.2.4 on 2021-06-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_alter_student_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='pic_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default='BAC', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='unidentified', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='unidentified', max_length=40),
        ),
    ]
