# Generated by Django 3.2.5 on 2021-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_auto_20210714_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='status_id',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
