# Generated by Django 3.2.5 on 2021-07-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_auto_20210717_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
