# Generated by Django 3.2.5 on 2021-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0018_rename_pic_id_staff_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('DCISM', 'Department of Computing,Information systems and Mathematics'), ('DBAF', 'Department of Banking, Finance and Economics'), ('DA', 'Department of Accountancy')], max_length=50),
        ),
    ]
