# Generated by Django 3.2.5 on 2021-08-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0020_alter_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pic',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
