# Generated by Django 3.2.5 on 2021-08-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_alter_staff_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='anchor_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='go_to',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
