# Generated by Django 3.2.5 on 2021-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0022_auto_20210812_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
