# Generated by Django 4.0.4 on 2022-05-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0023_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('BIT', 'Bachelor of Science in Information Technology'), ('BAC', 'Bachelor of Accountancy'), ('BAIT', 'Bachelor of Accountancy in Information Technology'), ('BBF', 'Bachelor of Banking and Finance'), ('BCS', 'Bachelor of Computer Science'), ('BEF', 'Bachelor of Economics and Finance')], max_length=50),
        ),
    ]
