# Generated by Django 4.0.4 on 2022-05-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_alter_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
